version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: bujo-darwin-amd64
    main: ./cmd/bujo
    binary: bujo
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.version={{.Version}}
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.commit={{.Commit}}
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.date={{.Date}}

  - id: bujo-darwin-arm64
    main: ./cmd/bujo
    binary: bujo
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.version={{.Version}}
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.commit={{.Commit}}
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.date={{.Date}}

  - id: bujo-linux-amd64
    main: ./cmd/bujo
    binary: bujo
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.version={{.Version}}
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.commit={{.Commit}}
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.date={{.Date}}

  - id: bujo-linux-arm64
    main: ./cmd/bujo
    binary: bujo
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.version={{.Version}}
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.commit={{.Commit}}
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.date={{.Date}}

  - id: bujo-windows
    main: ./cmd/bujo
    binary: bujo
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.version={{.Version}}
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.commit={{.Commit}}
      - -X github.com/typingincolor/bujo/cmd/bujo/cmd.date={{.Date}}

archives:
  - id: bujo
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: typingincolor
    name: bujo
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - name: bujo
    repository:
      owner: typingincolor
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/typingincolor/bujo"
    description: "A command-line Bullet Journal with local AI-powered summaries"
    license: "MIT"
    dependencies:
      - name: llama.cpp
    install: |
      bin.install "bujo"
    test: |
      system "#{bin}/bujo", "version"
    caveats: |
      To use local AI features, download a model:
        bujo model pull tinyllama

      Models are stored in ~/.bujo/models/

      For cloud AI, set GEMINI_API_KEY instead.
