name: Bug Report
description: Report a bug or issue
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the bug
      placeholder: What's wrong?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run command...
        2. Click on...
        3. See error...
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: What was supposed to happen?

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened? Include error messages if any.

  - type: dropdown
    id: area
    attributes:
      label: Bug Area
      description: Which part of the app is affected?
      options:
        - TUI (Terminal Interface)
        - CLI (Command Line)
        - Habits
        - Entries (Tasks/Notes/Events)
        - Goals
        - AI/Summaries
        - Search
        - Export/Import
        - Context (Location/Mood)
        - Other
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Context
      description: Any other details
      placeholder: Error logs, screenshots, environment details, etc.
