CREATE TABLE IF NOT EXISTS summaries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_id TEXT NOT NULL,
    horizon TEXT NOT NULL CHECK(horizon IN ('daily', 'weekly')),
    content TEXT NOT NULL,
    start_date DATETIME NOT NULL,
    end_date DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 1,
    valid_from DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to DATETIME,
    op_type TEXT NOT NULL DEFAULT 'INSERT' CHECK(op_type IN ('INSERT', 'UPDATE', 'DELETE'))
);
