// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChildEntry(arg1, arg2, arg3) {
  return window['go']['wails']['App']['AddChildEntry'](arg1, arg2, arg3);
}

export function AddEntry(arg1, arg2) {
  return window['go']['wails']['App']['AddEntry'](arg1, arg2);
}

export function AddListItem(arg1, arg2) {
  return window['go']['wails']['App']['AddListItem'](arg1, arg2);
}

export function AnswerQuestion(arg1, arg2) {
  return window['go']['wails']['App']['AnswerQuestion'](arg1, arg2);
}

export function ApplyEditableDocument(arg1, arg2) {
  return window['go']['wails']['App']['ApplyEditableDocument'](arg1, arg2);
}

export function ApplyEditableDocumentWithActions(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['App']['ApplyEditableDocumentWithActions'](arg1, arg2, arg3, arg4);
}

export function CancelEntry(arg1) {
  return window['go']['wails']['App']['CancelEntry'](arg1);
}

export function CancelGoal(arg1) {
  return window['go']['wails']['App']['CancelGoal'](arg1);
}

export function CancelListItem(arg1) {
  return window['go']['wails']['App']['CancelListItem'](arg1);
}

export function CreateGoal(arg1, arg2) {
  return window['go']['wails']['App']['CreateGoal'](arg1, arg2);
}

export function CreateHabit(arg1) {
  return window['go']['wails']['App']['CreateHabit'](arg1);
}

export function CreateList(arg1) {
  return window['go']['wails']['App']['CreateList'](arg1);
}

export function CyclePriority(arg1) {
  return window['go']['wails']['App']['CyclePriority'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['wails']['App']['DeleteEntry'](arg1);
}

export function DeleteGoal(arg1) {
  return window['go']['wails']['App']['DeleteGoal'](arg1);
}

export function DeleteHabit(arg1) {
  return window['go']['wails']['App']['DeleteHabit'](arg1);
}

export function DeleteList(arg1, arg2) {
  return window['go']['wails']['App']['DeleteList'](arg1, arg2);
}

export function EditEntry(arg1, arg2) {
  return window['go']['wails']['App']['EditEntry'](arg1, arg2);
}

export function EditListItem(arg1, arg2) {
  return window['go']['wails']['App']['EditListItem'](arg1, arg2);
}

export function GetAllMentions() {
  return window['go']['wails']['App']['GetAllMentions']();
}

export function GetAllTags() {
  return window['go']['wails']['App']['GetAllTags']();
}

export function GetAttentionResultType() {
  return window['go']['wails']['App']['GetAttentionResultType']();
}

export function GetAttentionScores(arg1) {
  return window['go']['wails']['App']['GetAttentionScores'](arg1);
}

export function GetDayEntries(arg1, arg2) {
  return window['go']['wails']['App']['GetDayEntries'](arg1, arg2);
}

export function GetEditableDocument(arg1) {
  return window['go']['wails']['App']['GetEditableDocument'](arg1);
}

export function GetEntry(arg1) {
  return window['go']['wails']['App']['GetEntry'](arg1);
}

export function GetEntryAncestors(arg1) {
  return window['go']['wails']['App']['GetEntryAncestors'](arg1);
}

export function GetEntryContext(arg1) {
  return window['go']['wails']['App']['GetEntryContext'](arg1);
}

export function GetGoals(arg1) {
  return window['go']['wails']['App']['GetGoals'](arg1);
}

export function GetHabits(arg1) {
  return window['go']['wails']['App']['GetHabits'](arg1);
}

export function GetInsightsActions() {
  return window['go']['wails']['App']['GetInsightsActions']();
}

export function GetInsightsActionsForWeek(arg1) {
  return window['go']['wails']['App']['GetInsightsActionsForWeek'](arg1);
}

export function GetInsightsDashboard() {
  return window['go']['wails']['App']['GetInsightsDashboard']();
}

export function GetInsightsDecisionLog() {
  return window['go']['wails']['App']['GetInsightsDecisionLog']();
}

export function GetInsightsDistinctTopics() {
  return window['go']['wails']['App']['GetInsightsDistinctTopics']();
}

export function GetInsightsInitiativeDetail(arg1) {
  return window['go']['wails']['App']['GetInsightsInitiativeDetail'](arg1);
}

export function GetInsightsInitiativePortfolio() {
  return window['go']['wails']['App']['GetInsightsInitiativePortfolio']();
}

export function GetInsightsSummaries(arg1) {
  return window['go']['wails']['App']['GetInsightsSummaries'](arg1);
}

export function GetInsightsSummaryDetail(arg1) {
  return window['go']['wails']['App']['GetInsightsSummaryDetail'](arg1);
}

export function GetInsightsSummaryForWeek(arg1) {
  return window['go']['wails']['App']['GetInsightsSummaryForWeek'](arg1);
}

export function GetInsightsTopicTimeline(arg1) {
  return window['go']['wails']['App']['GetInsightsTopicTimeline'](arg1);
}

export function GetInsightsWeeklyReport(arg1) {
  return window['go']['wails']['App']['GetInsightsWeeklyReport'](arg1);
}

export function GetLists() {
  return window['go']['wails']['App']['GetLists']();
}

export function GetLocationHistory() {
  return window['go']['wails']['App']['GetLocationHistory']();
}

export function GetOutstandingQuestions() {
  return window['go']['wails']['App']['GetOutstandingQuestions']();
}

export function GetOverdue() {
  return window['go']['wails']['App']['GetOverdue']();
}

export function GetVersion() {
  return window['go']['wails']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['wails']['App']['Greet'](arg1);
}

export function HasChildren(arg1) {
  return window['go']['wails']['App']['HasChildren'](arg1);
}

export function IsInsightsAvailable() {
  return window['go']['wails']['App']['IsInsightsAvailable']();
}

export function LogHabit(arg1, arg2) {
  return window['go']['wails']['App']['LogHabit'](arg1, arg2);
}

export function LogHabitForDate(arg1, arg2, arg3) {
  return window['go']['wails']['App']['LogHabitForDate'](arg1, arg2, arg3);
}

export function MarkEntryDone(arg1) {
  return window['go']['wails']['App']['MarkEntryDone'](arg1);
}

export function MarkEntryUndone(arg1) {
  return window['go']['wails']['App']['MarkEntryUndone'](arg1);
}

export function MarkGoalActive(arg1) {
  return window['go']['wails']['App']['MarkGoalActive'](arg1);
}

export function MarkGoalDone(arg1) {
  return window['go']['wails']['App']['MarkGoalDone'](arg1);
}

export function MarkListItemDone(arg1) {
  return window['go']['wails']['App']['MarkListItemDone'](arg1);
}

export function MarkListItemUndone(arg1) {
  return window['go']['wails']['App']['MarkListItemUndone'](arg1);
}

export function MigrateEntry(arg1, arg2) {
  return window['go']['wails']['App']['MigrateEntry'](arg1, arg2);
}

export function MigrateGoal(arg1, arg2) {
  return window['go']['wails']['App']['MigrateGoal'](arg1, arg2);
}

export function MoveEntryToList(arg1, arg2) {
  return window['go']['wails']['App']['MoveEntryToList'](arg1, arg2);
}

export function MoveEntryToRoot(arg1) {
  return window['go']['wails']['App']['MoveEntryToRoot'](arg1);
}

export function MoveListItem(arg1, arg2) {
  return window['go']['wails']['App']['MoveListItem'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['wails']['App']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['wails']['App']['ReadFile'](arg1);
}

export function RemoveListItem(arg1) {
  return window['go']['wails']['App']['RemoveListItem'](arg1);
}

export function RenameList(arg1, arg2) {
  return window['go']['wails']['App']['RenameList'](arg1, arg2);
}

export function ResolveDate(arg1) {
  return window['go']['wails']['App']['ResolveDate'](arg1);
}

export function RetypeEntry(arg1, arg2) {
  return window['go']['wails']['App']['RetypeEntry'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['wails']['App']['Search'](arg1);
}

export function SearchByMentions(arg1) {
  return window['go']['wails']['App']['SearchByMentions'](arg1);
}

export function SearchByTags(arg1) {
  return window['go']['wails']['App']['SearchByTags'](arg1);
}

export function SetHabitGoal(arg1, arg2) {
  return window['go']['wails']['App']['SetHabitGoal'](arg1, arg2);
}

export function SetHabitMonthlyGoal(arg1, arg2) {
  return window['go']['wails']['App']['SetHabitMonthlyGoal'](arg1, arg2);
}

export function SetHabitWeeklyGoal(arg1, arg2) {
  return window['go']['wails']['App']['SetHabitWeeklyGoal'](arg1, arg2);
}

export function SetLocation(arg1, arg2) {
  return window['go']['wails']['App']['SetLocation'](arg1, arg2);
}

export function SetMood(arg1, arg2) {
  return window['go']['wails']['App']['SetMood'](arg1, arg2);
}

export function SetPriority(arg1, arg2) {
  return window['go']['wails']['App']['SetPriority'](arg1, arg2);
}

export function SetWeather(arg1, arg2) {
  return window['go']['wails']['App']['SetWeather'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['wails']['App']['Shutdown'](arg1);
}

export function UncancelEntry(arg1) {
  return window['go']['wails']['App']['UncancelEntry'](arg1);
}

export function UncancelGoal(arg1) {
  return window['go']['wails']['App']['UncancelGoal'](arg1);
}

export function UncancelListItem(arg1) {
  return window['go']['wails']['App']['UncancelListItem'](arg1);
}

export function UndoHabitLog(arg1) {
  return window['go']['wails']['App']['UndoHabitLog'](arg1);
}

export function UndoHabitLogForDate(arg1, arg2) {
  return window['go']['wails']['App']['UndoHabitLogForDate'](arg1, arg2);
}

export function UpdateGoal(arg1, arg2) {
  return window['go']['wails']['App']['UpdateGoal'](arg1, arg2);
}

export function ValidateEditableDocument(arg1) {
  return window['go']['wails']['App']['ValidateEditableDocument'](arg1);
}
