// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgenda(arg1, arg2) {
  return window['go']['wails']['App']['GetAgenda'](arg1, arg2);
}

export function GetGoals(arg1) {
  return window['go']['wails']['App']['GetGoals'](arg1);
}

export function GetHabits(arg1) {
  return window['go']['wails']['App']['GetHabits'](arg1);
}

export function GetLists() {
  return window['go']['wails']['App']['GetLists']();
}

export function Greet(arg1) {
  return window['go']['wails']['App']['Greet'](arg1);
}

export function MarkEntryDone(arg1) {
  return window['go']['wails']['App']['MarkEntryDone'](arg1);
}

export function MarkEntryUndone(arg1) {
  return window['go']['wails']['App']['MarkEntryUndone'](arg1);
}

export function AddEntry(arg1, arg2) {
  return window['go']['wails']['App']['AddEntry'](arg1, arg2);
}

export function LogHabit(arg1, arg2) {
  return window['go']['wails']['App']['LogHabit'](arg1, arg2);
}

export function AddListItem(arg1, arg2) {
  return window['go']['wails']['App']['AddListItem'](arg1, arg2);
}

export function MarkListItemDone(arg1) {
  return window['go']['wails']['App']['MarkListItemDone'](arg1);
}

export function MarkListItemUndone(arg1) {
  return window['go']['wails']['App']['MarkListItemUndone'](arg1);
}

export function RemoveListItem(arg1) {
  return window['go']['wails']['App']['RemoveListItem'](arg1);
}

export function CreateGoal(arg1, arg2) {
  return window['go']['wails']['App']['CreateGoal'](arg1, arg2);
}

export function MarkGoalDone(arg1) {
  return window['go']['wails']['App']['MarkGoalDone'](arg1);
}

export function MarkGoalActive(arg1) {
  return window['go']['wails']['App']['MarkGoalActive'](arg1);
}

export function DeleteGoal(arg1) {
  return window['go']['wails']['App']['DeleteGoal'](arg1);
}

export function Search(arg1) {
  return window['go']['wails']['App']['Search'](arg1);
}
