// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {service} from '../models';
import {domain} from '../models';
import {wails} from '../models';

export function AddEntry(arg1:string,arg2:time.Time):Promise<Array<number>>;

export function AddListItem(arg1:number,arg2:string):Promise<number>;

export function AnswerQuestion(arg1:number,arg2:string):Promise<void>;

export function CancelEntry(arg1:number):Promise<void>;

export function CreateGoal(arg1:string,arg2:time.Time):Promise<number>;

export function CreateHabit(arg1:string):Promise<number>;

export function CreateList(arg1:string):Promise<number>;

export function CyclePriority(arg1:number):Promise<void>;

export function DeleteEntry(arg1:number):Promise<void>;

export function DeleteGoal(arg1:number):Promise<void>;

export function DeleteHabit(arg1:number):Promise<void>;

export function DeleteList(arg1:number,arg2:boolean):Promise<void>;

export function EditEntry(arg1:number,arg2:string):Promise<void>;

export function EditListItem(arg1:number,arg2:string):Promise<void>;

export function GetAgenda(arg1:time.Time,arg2:time.Time):Promise<service.MultiDayAgenda>;

export function GetGoals(arg1:time.Time):Promise<Array<domain.Goal>>;

export function GetHabits(arg1:number):Promise<service.TrackerStatus>;

export function GetLists():Promise<Array<wails.ListWithItems>>;

export function Greet(arg1:string):Promise<string>;

export function HasChildren(arg1:number):Promise<boolean>;

export function LogHabit(arg1:number,arg2:number):Promise<void>;

export function LogHabitForDate(arg1:number,arg2:number,arg3:time.Time):Promise<void>;

export function MarkEntryDone(arg1:number):Promise<void>;

export function MarkEntryUndone(arg1:number):Promise<void>;

export function MarkGoalActive(arg1:number):Promise<void>;

export function MarkGoalDone(arg1:number):Promise<void>;

export function MarkListItemDone(arg1:number):Promise<void>;

export function MarkListItemUndone(arg1:number):Promise<void>;

export function MigrateEntry(arg1:number,arg2:time.Time):Promise<number>;

export function RemoveListItem(arg1:number):Promise<void>;

export function RenameList(arg1:number,arg2:string):Promise<void>;

export function Search(arg1:string):Promise<Array<domain.Entry>>;

export function SetHabitGoal(arg1:number,arg2:number):Promise<void>;

export function SetMood(arg1:time.Time,arg2:string):Promise<void>;

export function SetPriority(arg1:number,arg2:string):Promise<void>;

export function SetWeather(arg1:time.Time,arg2:string):Promise<void>;

export function UncancelEntry(arg1:number):Promise<void>;

export function UndoHabitLog(arg1:number):Promise<void>;
